### ISSUE TITLE
sensor has started failing

### ISSUE THREAD

**Issue by kobbra** [youdroid/home-assistant-couchpotato#9]
Hi

my sensor has started failing with following error..

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    self.update  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/couchpotato/sensor.py", line 93, in update
    elif "release_date" in movie['info'] and len(movie['info']['release_date']['expires']) != 0:
TypeError: object of type 'int' has no len()

**Comment by kobbra** [comment]
Hi

FYI this was data related issue.. i had added a movie with release date that was "n/a" i deleted that movie from couchpotato and sensor started working again.

Br 
Martin

**Comment by youdroid** [comment]
Thank you for your feedback, I will fix that !
When I parse couchpotato result, I will catch movie with "n/a" value in release date.

Have a good day
